org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=false
# Optimization flags for gradle build
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
# NDK
android.ndkVersion=26.3.11579264
